# Generated by Django 4.0.2 on 2022-02-24 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0.0, verbose_name='total')),
                ('status', models.CharField(choices=[('A', 'Aproved'), ('C', 'Created'), ('R', 'Rejected'), ('P', 'Pending'), ('S', 'Sent'), ('F', 'Finished')], default='C', max_length=1, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='product')),
                ('product_id', models.PositiveIntegerField(verbose_name='product_id')),
                ('variation', models.CharField(max_length=100, verbose_name='variation')),
                ('variation_id', models.PositiveIntegerField(verbose_name='variation_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('promotional_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='promotional_price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('image', models.CharField(max_length=2000, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Items do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ('-created_at',),
            },
        ),
    ]
