# Generated by Django 4.0.2 on 2022-02-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
