# Generated by Django 4.0.2 on 2022-02-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_variation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('-price',), 'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.RemoveField(
            model_name='variation',
            name='inventory',
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='promo_price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Variable'), (2, 'Simple')], default=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='promo_price'),
        ),
    ]
