# Generated by Django 4.0.2 on 2022-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='name',
            new_name='variation_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
