# Generated by Django 4.0.2 on 2022-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_name_variation_variation_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
