# Generated by Django 4.0.2 on 2022-02-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('-price',), 'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='promotional price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='promotional price'),
        ),
    ]
