# Generated by Django 4.0.2 on 2022-02-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_options_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='promotional price'),
        ),
    ]
