# Generated by Django 4.0.2 on 2022-02-24 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='birth_date')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('address_number', models.CharField(max_length=5, verbose_name='number')),
                ('address_complement', models.CharField(max_length=30, verbose_name='complement')),
                ('address_neighborhood', models.CharField(max_length=30, verbose_name='neighborhood')),
                ('address_city', models.CharField(max_length=30, verbose_name='city')),
                ('address_state', localflavor.br.models.BRStateField(max_length=2)),
                ('address_cep', localflavor.br.models.BRPostalCodeField(max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
