# Generated by Django 4.0.2 on 2022-02-25 19:45

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF Document'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postalcode',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=localflavor.br.models.BRStateField(max_length=2, verbose_name='state'),
        ),
    ]
