# Generated by Django 4.0.2 on 2022-02-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_profile_cpf_alter_profile_postalcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
